# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'gbif_apidae'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'data_lakehouse'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
log-path: "logs"

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  gbif_apidae:
    # Configurações para a pasta 'staging' (Camada Silver)
    staging:
      +materialized: external
      +meta:
        format: parquet
    marts:
      +materialized: external
      +meta:
        format: parquet
flags:
  require_generic_test_arguments_property: true